# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-s settings.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: true
    sonarQubeRunAnalysis: false
    goals: 'deploy'


- task: DownloadPackage@1
  inputs:
    packageType: 'maven'
    feed: '/f5755216-8eea-4fbe-aa47-e97878edc8c7'
    view: 'c8bc3a46-2ab9-4809-8679-d5796d908e7b'
    definition: 'e5435290-8f90-4a02-8d39-0350817c1489'
    version: '1.0-snapshot'
    downloadPath: '$(System.ArtifactsDirectory)'